DO $roles$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'zabuni_owner') THEN
    CREATE ROLE zabuni_owner NOLOGIN
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'zabuni_migrator') THEN
    CREATE ROLE zabuni_migrator LOGIN PASSWORD 'zabuni_migrator'
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'zabuni_app') THEN
    CREATE ROLE zabuni_app LOGIN PASSWORD 'zabuni_app'
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END
$roles$;

ALTER ROLE zabuni_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
ALTER ROLE zabuni_migrator LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
ALTER ROLE zabuni_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
GRANT zabuni_owner TO zabuni_migrator;
REVOKE zabuni_owner, zabuni_migrator FROM zabuni_app;

REVOKE CONNECT ON DATABASE zabuni FROM PUBLIC;
GRANT CONNECT ON DATABASE zabuni TO zabuni_migrator, zabuni_app;
GRANT CREATE ON DATABASE zabuni TO zabuni_owner;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO zabuni_owner;
GRANT USAGE ON SCHEMA public TO zabuni_migrator;
GRANT USAGE ON SCHEMA public TO zabuni_app;
ALTER DEFAULT PRIVILEGES FOR ROLE zabuni_owner IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE zabuni_owner IN SCHEMA public REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE zabuni_owner IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM PUBLIC;
