-- Zabuni migrations are forward-only. UUIDv7 identifiers are generated by the application.
-- This intentionally avoids database extensions so the foundation works on local Postgres and Neon.

CREATE TABLE tenants (
  id uuid PRIMARY KEY,
  legal_name text NOT NULL,
  trading_name text,
  kra_pin text,
  vat_registered boolean NOT NULL DEFAULT false,
  etims_mode text,
  etims_branch_id text,
  timezone text NOT NULL DEFAULT 'Africa/Nairobi',
  currency char(3) NOT NULL DEFAULT 'KES',
  plan text NOT NULL,
  status text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tenants_legal_name_not_blank CHECK (btrim(legal_name) <> ''),
  CONSTRAINT tenants_etims_mode_check CHECK (etims_mode IS NULL OR etims_mode IN ('oscu', 'vscu')),
  CONSTRAINT tenants_currency_check CHECK (currency ~ '^[A-Z]{3}$')
);
